Feat: add planning tab
cbn-alpin/gn_module_conservation_strategy pull request #26
Opened 2023-01-05 13:49 UTC by ch-cbna

See #25

2023-01-06 09:56 UTC, jpm-cbna requested changes
Juste quelques petites remarques sur la forme.

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/strategy/planning/planning.component.ts
> +import { Subscription, Observable } from '@librairies/rxjs';
Pour les imports, ce qui est intéressant c'est de les répartir en 4 sections:
- la première : les imports Angular
- la seconde : les imports des librairies tierces
- la troisième : les imports des librairies GeoNature
- la quatrième : les imports des fichiers de notre module.

Chaque section est à séparer par un saut de ligne.

Là, il faudrait mettre l'import rxjs de la ligne 12 dans la seconde section plutôt.

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +        [matTooltip]="assessment.assessmentDate | date: 'medium':undefined:'fr'"
L'espace après `date:` me semble à supprimer mais j'ai l'impression qu'il est présent partout dans le rester du code et pour d'autre Pipe. Il faut vérifier si c'est Prettier qui le rajoute.

Si c'est bien ajouter par Prettier le laisser sinon l'enlever partout...

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +                >&nbsp;-&nbsp;</span
Il serait plus lisible de mettre à la ligne en l'indentant le contenu de la balise `span`.

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +              >event_available</mat-icon
Idem, mettre à la ligne et indenter le contenu de `mat-icon`.

D'une manière générale, je trouve ce type de formatage généré par Prettier pas très lisible. C'est pourquoi, je pense qu'il vaut mieux mettre à la ligne le contenu et indenter sauf dans les cas où l'ajout d'espace autour du contenu pose problème... Qu'en penses tu ?

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.ts
> +    if (!this.actionIdSelected || this.actionIdSelected !== id) { // prevent for looping twice because of expanded
Il vaut mieux mettre le commentaire juste avant le if plutôt que juste après l'ouverture de l'accolade. Sinon, une partie du commentaire peut être "tronqué" et donc moins lisible suivant la taille de l'affichage...

Mettre une majuscule au début de chaque commentaire.

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessments-list.component.ts
> +    // console.log(this.assessmentIdSelected);
Supprimer ces 3 lignes.

2023-01-06 09:56 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessments-list.component.ts
> +    if (!this.assessmentIdSelected || this.assessmentIdSelected !== id) { // prevent for looping twice because of expanded
Mettre le commentaire avant le `if`.

2023-01-10 08:33 UTC, jpm-cbna requested changes
Juste des propositions d'amélioration des requêtes de mise à jour.

2023-01-10 09:00 UTC, ch-cbna commented on frontend/app/strategy/planning/planning.component.ts
> +    if (task.actionId) {
est-ce que c'est la bonne méthode ? 

```
  detectTypeOfTask(task) {
    let url = [
      '/conservation_strategy/territories',
      task.territoryCode,
      'priority-taxa',
      task.priorityTaxonId,
      { shortName: task.taxonName },
      'assessments',
      task.assessmentId
    ];
    if (task.actionId) {
      url = url.push('actions', task.actionId);
    }
    return url;
  }
```
  j'ai un erreur sur le deuxième "url" : _Type 'number' is not assignable to type 'any[]'._

2023-01-10 10:37 UTC, ch-cbna commented on frontend/app/strategy/planning/planning.component.html
> +            'bg-danger': row.progressStatus == 'À mettre en place'
row ne contient pas le code de progressStatus, comment tester sur le code ?

2023-01-10 10:44 UTC, jpm-cbna commented on frontend/app/strategy/planning/planning.component.ts
> +    if (task.actionId) {
Je pense que tu n'as pas besoin d'assigner le retour de `url.push()` à `url` car `push()` retourne la nouvelle valeur de la propriété length de l'objet sur lequel la méthode a été appelée. Il faut seulement faire : `url.push('actions', task.actionId);`

2023-01-10 13:42 UTC, jpm-cbna requested changes

2023-01-10 13:42 UTC, jpm-cbna commented on docs/update_nomenclatures.sql
> +	id_nomenclature = get_id_nomenclature_type('rbs');
Non, tu ne peux pas utiliser cette fonction ici car c'est un `id_nomenclature` que l'on veut. Il te faut utiliser celle ci : `ref_nomenclatures.get_id_nomenclature('CS_ACTION', 'rbs')`.
Il faut corriger aussi les autres requêtes.

2023-01-10 13:42 UTC, jpm-cbna commented on docs/update_nomenclatures.sql
> +	"hierarchy" = concat(get_id_nomenclature_type('CS_ACTION'), '.003'),
Je ne suis pas certain qu'il trouve la fonction si tu ne précise pas le schéma où elle se situe. À tester, si possible.
Dans notre cas, c'est `ref_nomenclatures.get_id_nomenclature_type('CS_ACTION')`

2023-01-10 13:42 UTC, jpm-cbna commented on docs/update_nomenclatures.sql
> +	"hierarchy" = concat(get_id_nomenclature_type('CS_ACTION'), '.003'),
Si possible, mettre les noms des fonctions Postgresql en majuscule : `CONCAT()` plutôt que `concat()`. Cela permet de mieux les distinguer nos fonctions que  nous laissons en minuscule : `get_id_nomenclature_type()`.

2023-01-10 13:56 UTC, ch-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +        [matTooltip]="assessment.assessmentDate | date: 'medium':undefined:'fr'"
c'est bien Prettier qui ajoute l'espace après ":"

2023-01-10 13:59 UTC, ch-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +              >event_available</mat-icon
oui je trouve aussi que c'est pas super lisible à la manière de Prettier.. je trouve ça plus lisible aussi si le contenu est sur une autre ligne et indenté

2023-01-10 14:05 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +              >event_available</mat-icon
Ok, alors nous mettrons à la ligne quand c'est possible. Normalement, une fois mis à la ligne Prettier ne fait plus de modification.

2023-01-10 14:06 UTC, jpm-cbna approved these changes

2023-01-10 14:38 UTC, ch-cbna commented on docs/update_nomenclatures.sql
> +	"hierarchy" = concat(get_id_nomenclature_type('CS_ACTION'), '.003'),
il trouve bien la fonction sans préciser le schéma

2023-01-10 16:41 UTC, jpm-cbna commented on frontend/app/taxon-detail/assessments-list/assessment-detail/assessment-detail.component.html
> +        [matTooltip]="assessment.assessmentDate | date: 'medium':undefined:'fr'"
Ok, alors on laisse avec l'espace...

2023-01-11 10:42 UTC, merged